import{s as c}from"./db_conn.js";async function g(a,e,t){const{data:n,error:s}=await c.from("produk_varian").select("jumlah_stok").eq("id",a).single();if(s)return console.error("Error fetching variant stock:",s),null;let i=n.jumlah_stok;t==="pembelian"||t==="penyesuaian_masuk"?i+=e:(t==="penjualan"||t==="penyesuaian_keluar")&&(i-=e);const{error:o}=await c.from("produk_varian").update({jumlah_stok:i}).eq("id",a);return o?(console.error("Error updating variant stock:",o),null):i}async function v(a,e){const{data:t}=await c.from("riwayat_stok").select("id, qty, stok_sisa, harga, tanggal").eq("id_varian",a).eq("tipe_riwayat","pembelian").gt("stok_sisa",0).order("tanggal",{ascending:!0}).limit(100);let n=e,s=0;const i=[],o=[];for(const r of t){if(n<=0)break;const l=Math.min(n,r.stok_sisa);s+=l*r.harga,n-=l,i.push({id:r.id,newRemaining:r.stok_sisa-l}),o.push({usedQty:l,purchasePrice:r.harga,purchaseDate:r.tanggal})}return i.length>0&&await c.rpc("batch_update_remaining",{updates:i.map(r=>({id:r.id,remaining:r.newRemaining}))}),{averageHpp:s/e,consumptionRecords:o,hasPartialConsumption:o.length>1}}async function S({variantId:a=null,type:e=null,id:t=null,quantity:n=null,price:s=null,date:i=new Date().toISOString()}){try{if(!a||!e||n===null)throw new Error("Missing required parameters");const{data:o,error:r}=await c.from("produk_varian").select("jumlah_stok").eq("id",a).single();if(r)throw r;const l=o.jumlah_stok;if(e==="pembelian"||e==="penyesuaian_masuk"){let u=l;if(e==="penyesuaian_masuk"&&(u=await g(a,n,e),u===null))throw new Error("Failed to update variant stock");const{data:p,error:d}=await c.from("riwayat_stok").insert([{id_varian:a,tipe_riwayat:e,qty:n,stok_sisa:n,saldo:u,harga:s,hpp:null,tanggal:i,id_referensi:t}]).select();if(d)throw d;return{success:!0,newStock:u,records:p,isMultiRecord:!1}}if(e==="penjualan"||e==="penyesuaian_keluar"){const{averageHpp:u,consumptionRecords:p,hasPartialConsumption:d}=await v(a,n);if(d){const f=[];let _=l;for(const m of p)_-=m.usedQty,f.push({id_varian:a,tipe_riwayat:e,qty:m.usedQty,stok_sisa:null,saldo:_,harga:s,hpp:m.purchasePrice,tanggal:i,id_referensi:t});const k=await g(a,n,e);if(k===null)throw new Error("Failed to update variant stock");const{error:b}=await c.from("riwayat_stok").insert(f);if(b)throw b;return{success:!0,newStock:k,records:f,isMultiRecord:!0}}const h=await g(a,n,e);if(h===null)throw new Error("Failed to update variant stock");const{data:y,error:w}=await c.from("riwayat_stok").insert([{id_varian:a,tipe_riwayat:e,qty:n,stok_sisa:null,saldo:h,harga:s,hpp:u,tanggal:i,id_referensi:t}]).select();if(w)throw w;return{success:!0,newStock:h,records:y,isMultiRecord:!1}}throw new Error("Invalid transaction type")}catch(o){throw console.error("Error in processEntry:",o),o}}async function E(){try{const a=new Date,e=new Date(a),t=new Date(a);e.setMonth(e.getMonth()-1),t.setMonth(t.getMonth()-3);const{data:n,error:s}=await c.from("pesanan_pembelian").select(`
                id,
                tanggal_diterima,
                supplier: id_supplier(perusahaan, cp)
            `).eq("status_pesanan","diterima").lt("tanggal_diterima",e.toISOString().split("T")[0]);if(s)throw s;return(n||[]).map(o=>{const r=new Date(o.tanggal_diterima);let l="1_bulan";return r<t&&(l="3_bulan"),{...o,overdueType:l}})}catch(a){return console.error("Error checking unpaid orders:",a),[]}}async function j(){const a=document.getElementById("unpaidBannerRow"),e=document.getElementById("unpaidBanner");if(!a||!e){console.warn("[WARN] unpaidBanner or unpaidBannerRow container not found.");return}e.innerHTML="",a.style.display="none";const t=await E();if(t.length===0)return;a.style.display="flex";const n=document.createElement("div");n.className="unpaid-notice-banner alert alert-danger d-flex justify-content-between align-items-center mb-0";let s="";const i=t.filter(r=>r.overdueType==="1_bulan").length,o=t.filter(r=>r.overdueType==="3_bulan").length;o>0&&(s+=`⚠️ ${o} pesanan sudah lewat 3 bulan dan belum dibayar. `),i>0&&(s+=`${i} pesanan sudah lewat 1 bulan dan belum dibayar. `),s+='<a href="/pembelian.html" style="color: #a30000; text-decoration: underline;">Lihat daftar pesanan</a>',n.innerHTML=`
        <div class="container-fluid d-flex justify-content-between align-items-center py-2">
            <div class="d-flex align-items-center">
                <i class="bi bi-exclamation-triangle-fill me-2"></i>
                <span>${s}</span>
            </div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    `,e.appendChild(n),n.querySelector(".btn-close").addEventListener("click",()=>{n.remove(),e.hasChildNodes()||(a.style.display="none")})}export{j as d,S as p,g as u};
